# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"$\n\x13ValidateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\":\n\x14ValidateUserResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x10\n\x08username\x18\x02 \x01(\t2T\n\x0b\x41uthService\x12\x45\n\x0cValidateUser\x12\x19.auth.ValidateUserRequest\x1a\x1a.auth.ValidateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATEUSERREQUEST']._serialized_start=20
  _globals['_VALIDATEUSERREQUEST']._serialized_end=56
  _globals['_VALIDATEUSERRESPONSE']._serialized_start=58
  _globals['_VALIDATEUSERRESPONSE']._serialized_end=116
  _globals['_AUTHSERVICE']._serialized_start=118
  _globals['_AUTHSERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
