services:
  redis:
    image: redis:8.0-M02-alpine
    container_name: redis-test
    ports:
      - 6379:6379
    networks:
      - dodgygeezers_test

  event-service:
      # restart: "no"
    ports:
      - 8001:8001
      - 5679:5679
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-microservice-test
    volumes:
    - ./app:/app/app
    - ./pyproject.toml:/app/pyproject.toml
    - ./uv.lock:/app/uv.lock
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - python3
      - -Xfrozen_modules=off
      - -m
      - debugpy
      - --listen
      - 0.0.0.0:5679
      - --wait-for-client
      - -m
      - uvicorn
      - app.main:app
      - --reload
      - --host
      - "0.0.0.0"
      - --port
      - "8001"
    env_file:
      - .env.development
    environment:
      - DB_HOST=postgres
      - PYDEVD_DISABLE_FILE_VALIDATION=1
    networks:
      - dodgygeezers_test
    depends_on:
      - redis

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker-test
    command:
      - celery
      - -A
      - app.core.celery_config.celery_app
      - worker
      - --loglevel=info
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env.development
    networks:
      - dodgygeezers_test
    depends_on:
      - redis
      - event-service

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-beat-test
    command:
      - celery
      - -A
      - app.core.celery_config.celery_app
      - beat
      - --loglevel=info
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env.development
    networks:
      - dodgygeezers_test
    depends_on:
      - redis
      - event-service

  flower:
    image: mher/flower:latest
    container_name: flower-test
    ports:
      - 5555:5555
    environment:
      - FLOWER_BASIC_AUTH=username:password
      - FLOWER_BROKER=redis://redis:6379
    networks:
      - dodgygeezers_test
    depends_on:
      - redis
      - celery-worker

networks:
  dodgygeezers_test:
    # driver: bridge
    external: true