services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - dodgygeezers_video_test
  
  videoservice:
      # restart: "no"
    ports:
      - 8000:8000
      - 5678:5678
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'video_rest'
    volumes:
    - ./app:/app/app
    - ./pyproject.toml:/app/pyproject.toml
    - ./uv.lock:/app/uv.lock
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - python3
      - -Xfrozen_modules=off
      - -m
      - debugpy
      - --listen
      - 0.0.0.0:5678
      - --wait-for-client
      - -m
      - uvicorn
      - app.main:app
      - --reload
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
    # env_file:
    #   - .env.development
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - dodgygeezers_video_test

volumes:
  redis_data:

networks:
  dodgygeezers_video_test:
    driver: bridge
